### ISSUE TITLE
demo for Visium data

### ISSUE THREAD

**Issue by biopzhang** [daviddaiweizhang/istar#2]
Hello,

Thanks for the great tool! Could you please provide a tutorial for Visium data? The links to Visium in the README are broken. 

I'm following your instructions to prepare the input. I'm not quite sure about the definition of the pixel size (raw) and how to set the desired pixel size. Does the pixel size (raw) mean how many micrometers in one-pixel length in the he-raw.jpg?

Thanks in advance!
Pengzhi

**Comment by daviddaiweizhang** [comment]
Hi Pengzhi,

Thank you for your interest in iStar. I just fixed the broken links to Visium's documentation. In general, iStar can handle spatial transcriptomic data collected by any platform, including but not limited to Visium. As long as you can convert the data into the input format of iStar, the pipeline should run without a problem.

For the pixel size (raw), yes, it is the side length of the a pixel in `he-raw.jpg`, as described in the README. For example, if the size of each pixel in your `he-raw.jpg` is 0.2 um by 0.2 um, the value in your `pixel-size-raw.txt` should be 0.2.

Best,
David

**Comment by biopzhang** [comment]
Thank you for the explanation, David.
