### ISSUE TITLE
online version not working for example data

### ISSUE THREAD

**Issue by lingxin08** [daviddaiweizhang/istar#23]
Hi, 
   I tried the online version of this method, I downloaded the example data in the tutorial, but got this error. 
<img width="1235" alt="Screenshot 2024-09-09 at 11 22 54 PM" src="https://github.com/user-attachments/assets/cf0e25dc-d6a2-4f7f-9186-115477b46574">

**Comment by daviddaiweizhang** [comment]
There were some system problems with the server and have been fixed. The web app is working on the demo data as of today.
